### ISSUE TITLE
[Bug] Profile overview (in group), "Do you recommend (page name)" are broken

### ISSUE THREAD

**Issue by ReporterX** [FlandreDaisuki/Facebook-Dont-Track-Me#2]
**Describe the bug**
1. "Do you recommend (page name)?" is broken
Example: Go to https://www.facebook.com/pg/vkhreview/reviews/  
Try to click "yes" or "no". It won't work.

2. Visit https://www.facebook.com/groups/784883728554927/ (as an example)  
Click on any poster's profile link.  
Expected: The overview about the user activity in that group will pop up.  
Actual: Nothing pops up.  

**Environment**  
Firefox 66.0.2 (64-bit)
Facebook Don't Track Me 1.5.0

**Suggestion**  
Facebook keeps changing.  
It would be great if there is a button to toggle the addon (enable/disable). If some features are broken due to the removal of parameters, I can quickly toggle it. Thank you.

**Comment by FlandreDaisuki** [comment]
My facebook have no these feature as you said, so that I don't know what happen about this.

Facebook usually use AB test to publish their webpage. I'll fix it when mine been updated.

Disable button is a good idea, I'll add it when I have time.

Finally, thanks for your feedback. ❤️️

**Comment by FlandreDaisuki** [comment]
Well, I found this bug in other pages in my account, I'll fix it asap.
