### ISSUE TITLE
Facebook-Dont-Track-Me interferes with Yahoo Mail

### ISSUE THREAD

**Issue by aquila-XP** [FlandreDaisuki/Facebook-Dont-Track-Me#8]
The bug appears out of Facebook site.
I use Windows 10 Enterprise 2015 LTSB and Mozilla Firefox Browser v79.0 64bit with "Facebook Don't Track Me" v1.6.3 on my desktop configuration.
When is active, the extensions block some redirect link of Yahoo (https://mail.yahoo.com/d/folders/1?guce_referrer=gibberish&guce_referrer_sig=gibberish) and I'm unable to see my emails in Yahoo.
I get this message: "The page isn’t redirecting properly. Firefox has detected that the server is redirecting the request for this address in a way that will never complete."
The same extension is installed on my laptop with Windows 10 Enterprise 2018 LTSC and Mozilla Firefox Browser v79.0 64bit with "Facebook Don't Track Me" v1.6.3, but on this configuration I did not encounter any issues with the extension.

**Comment by FlandreDaisuki** [comment]
In your case, can you redirect to your mail by following link?

- https://mail.yahoo.com/d/folders/1?guce_referrer=gibberish&guce_referrer_sig=gibberish 
- https://mail.yahoo.com/d/folders/1

If true, I think there are some other wrong. I can normally use the yahoo mail.

Can you record a video to show your networking state? (<kbd>F12</kbd> => networking tab) or turn on the display log checkbox on this extension setting page and go `about:debugging#/runtime/this-firefox` ,inspect this extension to record logs to me.

- - -

What I want to know/see:

- What link you click? (short-url service? redirect service?)
- How the link route to that error?
- What web-extensions you install? (Maybe conflict with other web-extensions)

Log text can paste on secret gist and video can send private youtube link to me if you don't want show these publicly.

**Comment by aquila-XP** [comment]
Hi FlandreDaisuki,

The issue appeared when I tried to login to Yahoo Mail from `https://login.yahoo.com/?.src=ym&.intl=us.` I entered the ID and password and the first page that opened was `https://us.yahoo.com/.` And in a split of second I was redirected to `https://mail.yahoo.com/` and then the page never loaded.
I replaced some alphanumeric characters from `https://mail.yahoo.com/d/folders/1?guce_referrer=gibberish&guce_referrer_sig=gibberish` URL with the word `gibberish`.
I did not use any short-url service or redirect service.
I tried to remove the extra garbage from URL and to use the link directly `(https://mail.yahoo.com/d/folders/1)` but still did not work.
I disabled manually all the webextensions installed and in this way I found the culprit one.
I have 65 extensions installed in Firefox, mostly are privacy and content blocking oriented add-ons (uBlock Origin, Ghostery and Privacy Badger).
Maybe your extension could conflict with some redirect webextensions that I have installed: Universal Bypass, Twitter Link Deobfuscator, Tracking Token Stripper, Skip Redirect, Request Control, Redirect AMP to HTML, Pure URL, Neat URL, Google search link fix, Don't touch my tabs! (rel=noopener), and ClearURLs.
Unfortunately I'm not able to reproduce the error again, because it seems to work properly now.

**Comment by FlandreDaisuki** [comment]
well, if you find the extension that conflict with mine, plz let me know.
I think the issue can be close because there is no clue to debug & work fine now. 😎

And, thanks your report with details.
